=== Haven-King/Proximity/run/templates/normal/template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Template" type="TemplateType"/>
  <xs:simpleType name="color">
    <xs:annotation>
      <xs:documentation>The color entity indicates the color of an element. Color may be represented as hexadecimal RGB triples, as in HTML, or as hexadecimal ARGB tuples, with the A indicating alpha of transparency. An alpha value of 00 is totally transparent; FF is totally opaque. If RGB is used, the A value is assumed to be FF. For instance, the RGB value "#800080" represents purple. An ARGB value of "#40800080" would be a transparent purple. As in SVG 1.1, colors are defined in terms of the sRGB color space (IEC 61966).</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:token">
      <xs:pattern value="#[\dA-F]{6}([\dA-F][\dA-F])?"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="capitalization">
    <xs:restriction base="xs:string">
      <xs:enumeration value="default"/>
      <xs:enumeration value="all_caps"/>
      <xs:enumeration value="no_caps"/>
      <xs:enumeration value="small_caps"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="text_alignment_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="left"/>
      <xs:enumeration value="center"/>
      <xs:enumeration value="right"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="content_alignment_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="start"/>
      <xs:enumeration value="middle"/>
      <xs:enumeration value="end"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="EnumerationValueType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="value" use="optional"/>
        <xs:attribute type="xs:string" name="id" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="EnumerationType">
    <xs:sequence>
      <xs:element type="EnumerationValueType" name="EnumerationValue" maxOccurs="unbounded" minOccurs="2"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="default" use="required"/>
  </xs:complexType>
  <xs:complexType name="ToggleOptionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:boolean" name="default" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="StringOptionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="value"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="optionsType">
    <xs:sequence>
      <xs:element type="EnumerationType" name="Enumeration" minOccurs="0"  maxOccurs="unbounded"/>
      <xs:element type="ToggleOptionType" name="ToggleOption" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="StringOptionType" name="StringOption" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LayerPropertyType">
    <xs:sequence>
      <xs:element type="conditionsType" name="conditions"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AttributeModifierType">
    <xs:simpleContent>
      <xs:extension base="conditionsType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="StyleType" mixed="true">
    <xs:complexContent>
      <xs:extension base="LayerPropertyType">
        <xs:sequence>
          <xs:element type="TextShadowType" name="shadow" minOccurs="0" maxOccurs="1"/>
          <xs:element type="TextOutlineType" name="outline" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="font" use="optional"/>
        <xs:attribute type="xs:string" name="italicFont" use="optional"/>
        <xs:attribute type="capitalization" name="capitalization" use="optional"/>
        <xs:attribute type="color" name="color" use="optional"/>
        <xs:attribute type="xs:int" name="size" use="optional"/>
        <xs:attribute type="xs:float" name="kerning" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="stylesType">
    <xs:sequence>
      <xs:element type="StyleType" name="Style" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RangeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="key" use="required"/>
        <xs:attribute type="xs:int" name="min" use="optional"/>
        <xs:attribute type="xs:int" name="max" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ConditionDefinitionType">
    <xs:simpleContent>
      <xs:extension base="conditionsType">
        <xs:attribute type="xs:string" name="name" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="condition_definitionsType">
    <xs:sequence>
      <xs:element type="ConditionDefinitionType" name="ConditionDefinition" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="IsEqualsType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="key" use="required"/>
        <xs:attribute type="xs:string" name="value" use="optional" default="true"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IsPresentType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="key" use="required"/>
        <xs:attribute type="xs:boolean" name="value" use="optional" default="true"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="conditionsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="IsEqualsType" name="IsEquals"/>
      <xs:element type="IsPresentType" name="IsPresent"/>
      <xs:element type="RangeType" name="Range"/>
      <xs:element type="conditionsType" name="Or"/>
      <xs:element type="conditionsType" name="And"/>
      <xs:element type="conditionsType" name="Not" minOccurs="0"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="LayerType">
    <xs:sequence>
      <xs:element type="conditionsType" name="conditions"/>
      <xs:element type="StyleType" name="Style"/>
      <xs:element type="wrapType" name="wrap"/>
      <xs:element type="AttributeModifierType" name="AttributeModifier" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
    <xs:attribute type="xs:int" name="x"/>
    <xs:attribute type="xs:int" name="y"/>
  </xs:complexType>
  <xs:complexType name="ArtLayerType">
    <xs:complexContent>
      <xs:extension base="LayerType">
        <xs:attribute type="xs:string" name="width"/>
        <xs:attribute type="xs:string" name="height"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SVGLayerType">
    <xs:complexContent>
      <xs:extension base="LayerType">
        <xs:attribute type="xs:string" name="src" use="optional"/>
        <xs:attribute type="xs:int" name="width" use="optional"/>
        <xs:attribute type="xs:int" name="height" use="optional"/>
        <xs:attribute type="content_alignment_type" name="vertical_alignment" default="middle"/>
        <xs:attribute type="content_alignment_type" name="horizontal_alignment" default="middle"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ImageLayerType" mixed="true">
    <xs:complexContent>
      <xs:extension base="LayerType">
        <xs:sequence>
          <xs:element type="conditionsType" name="conditions" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="src" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="LayoutType">
    <xs:complexContent>
      <xs:extension base="GroupType">
        <xs:attribute name="width" type="xs:int" use="optional"/>
        <xs:attribute name="height" type="xs:int" use="optional"/>
        <xs:attribute name="alignment" type="content_alignment_type"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="GroupType">
    <xs:complexContent>
      <xs:extension base="LayerType">
        <xs:sequence>
          <xs:element type="ImageLayerType" name="ImageLayer"/>
          <xs:element type="GroupType" name="Selector"/>
          <xs:element type="ForkType" name="Fork"/>
          <xs:element type="TextLayerType" name="TextLayer"/>
          <xs:element type="GroupType" name="Group"/>
          <xs:element type="SpacingLayerType" name="SpacingLayer" minOccurs="0"/>
          <xs:element type="LayoutType" name="HorizontalLayout"/>
          <xs:element type="LayoutType" name="VerticalLayout"/>
          <xs:element type="SVGLayerType" name="SVG"/>
          <xs:element type="ArtLayerType" name="ArtLayer">
            <xs:annotation>
              <xs:documentation>The art layer is special in that it can also contain a width and/or height
                If both are provided, the layer will be stretched or shrunk to cover that area
                If only one is provided, the layer will be stretched or shrunk to fit that dimension
                while keeping the image proportional with its original dimensions</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element type="SquishBoxType" name="SquishBox"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BranchType" mixed="true">
    <xs:simpleContent>
      <xs:extension base="conditionsType">
        <xs:attribute type="xs:string" name="id" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="branchesType">
    <xs:sequence>
      <xs:element type="BranchType" name="Branch" maxOccurs="unbounded" minOccurs="2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ForkType">
    <xs:complexContent>
      <xs:extension base="GroupType">
        <xs:sequence>
          <xs:element type="branchesType" name="branches" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TextLayerType" mixed="true">
    <xs:complexContent>
      <xs:extension base="LayerType">
        <xs:sequence>
          <xs:element type="wrapType" name="wrap" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="text_alignment_type" name="alignment" use="optional" default="left"/>
        <xs:attribute type="xs:string" name="value" use="required"/>
        <xs:attribute type="xs:int" name="width" use="optional"/>
        <xs:attribute type="xs:int" name="height" use="optional"/>
        <xs:attribute type="xs:string" name="style" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="layersType">
    <xs:simpleContent>
      <xs:extension base="GroupType"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SquishBoxType">
    <xs:complexContent>
      <xs:extension base="LayerType">
        <xs:sequence>
          <xs:element type="GroupType" name="main"/>
          <xs:element type="GroupType" name="flex"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TextShadowType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="color" name="color" use="required"/>
        <xs:attribute type="xs:int" name="dX" use="required"/>
        <xs:attribute type="xs:int" name="dY" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TextOutlineType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="color" name="color" use="required"/>
        <xs:attribute type="xs:int" name="weight" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SpacingLayerType">
    <xs:simpleContent>
      <xs:extension base="LayerType">
        <xs:attribute type="xs:int" name="x"/>
        <xs:attribute type="xs:int" name="y"/>
        <xs:attribute type="xs:int" name="width" use="required"/>
        <xs:attribute type="xs:int" name="height" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="wrapType">
    <xs:complexContent>
      <xs:extension base="LayerPropertyType">
        <xs:attribute type="xs:int" name="x" use="optional"/>
        <xs:attribute type="xs:int" name="y" use="optional"/>
        <xs:attribute type="xs:int" name="width" use="optional"/>
        <xs:attribute type="xs:int" name="height" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TemplateType">
    <xs:sequence>
      <xs:element type="optionsType" name="options" minOccurs="0" maxOccurs="1"/>
      <xs:element type="stylesType" name="styles" minOccurs="0" maxOccurs="1"/>
      <xs:element type="condition_definitionsType" name="condition_definitions" minOccurs="0" maxOccurs="1"/>
      <xs:element type="layersType" name="layers"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="author"/>
    <xs:attribute type="xs:string" name="width" use="required"/>
    <xs:attribute type="xs:string" name="height" use="required"/>
  </xs:complexType>
</xs:schema>

=== Haven-King/Proximity/run/templates/normal/template.xml
<?xml version="1.0"?>

<Template name="Chilli's" author="ChilliAxe and Haven King" width="3288"
          height="4488"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="template.xsd">
    <options>
        <Enumeration id="border" default="black">
            <EnumerationValue value="black"/>
            <EnumerationValue value="gold" id="gold"/>
            <EnumerationValue value="silver"/>
            <EnumerationValue value="none"/>
        </Enumeration>
        <ToggleOption id="bottom_text_outline" default="false"/>
        <ToggleOption id="copyright" default="true"/>
        <ToggleOption id="flavor_text" default="true"/>
        <ToggleOption id="flavor_bar" default="true"/>
    </options>
    <condition_definitions>
        <ConditionDefinition name="colorless_artifact">
            <IsPresent key="proximity.types.artifact"/>
            <IsEquals key="proximity.color_count" value="0"/>
        </ConditionDefinition>
        <ConditionDefinition name="one_or_two_colors">
            <Range key="proximity.color_count" min="1" max="2"/>
        </ConditionDefinition>
    </condition_definitions>
    <layers>
        <!-- The art layer is special in that it can also contain a width and/or height
        If both are provided, the layer will be stretched or shrunk to cover that area
        If only one is provided, the layer will be stretched or shrunk to fit that dimension
        while keeping the image proportional with its original dimensions -->
        <ArtLayer x="352" y="605" width="2584" height="1882">
            <conditions>
                <IsEquals key="proximity.options.use_official_art"/>
            </conditions>
        </ArtLayer>
        <Selector id="backgrounds">
            <Selector id="nyx">
                <ImageLayer id="artifact">
                    <conditions>
                        <IsPresent key="proximity.types.artifact"/>
                    </conditions>
                </ImageLayer>
                <ImageLayer id="colorless">
                    <conditions>
                        <IsEquals key="proximity.color_count" value="0"/>
                    </conditions>
                </ImageLayer>
                <ImageLayer id="colored" src="${colors}">
                    <conditions>
                        <IsEquals key="proximity.color_count" value="1"/>
                    </conditions>
                </ImageLayer>
                <ImageLayer id="gold"/>
                <conditions>
                    <IsPresent key="frame_effects.nyxtouched"/>
                </conditions>
            </Selector>
            <Selector id="standard">
                <ImageLayer id="vehicle">
                    <conditions>
                        <IsPresent key="proximity.types.vehicle"/>
                    </conditions>
                </ImageLayer>
                <ImageLayer id="artifact">
                    <conditions>
                        <IsPresent key="proximity.types.artifact"/>
                        <IsPresent key="proximity.types.land" value="false"/>
                    </conditions>
                </ImageLayer>
                <ImageLayer id="land">
                    <conditions>
                        <IsPresent key="proximity.types.land"/>
                    </conditions>
                </ImageLayer>
                <ImageLayer id="colored" src="${colors}">
                    <conditions>
                        <Or>
                            <IsEquals key="proximity.color_count" value="1"/>
                            <And>
                                <IsEquals key="proximity.color_count" value="2"/>
                                <IsEquals key="proximity.hybrid"/>
                            </And>
                        </Or>
                    </conditions>
                </ImageLayer>
                <ImageLayer id="gold">
                    <conditions>
                        <Range key="proximity.color_count" min="2"/>
                    </conditions>
                </ImageLayer>
            </Selector>
            <conditions>
                <Not>
                    <IsEquals key="proximity.options.border" value="none"/>
                </Not>
            </conditions>
        </Selector>
        <Selector id="shadows">
            <ImageLayer id="legendary">
                <conditions>
                    <IsPresent key="proximity.types.legendary"/>
                </conditions>
            </ImageLayer>
            <ImageLayer id="mdfc">
                <conditions>
                    <IsEquals key="layout" value="modal_dfc"/>
                </conditions>
            </ImageLayer>
            <ImageLayer id="transform">
                <conditions>
                    <IsEquals key="layout" value="transform"/>
                </conditions>
            </ImageLayer>
            <ImageLayer id="normal"/>
        </Selector>
        <Selector id="pinlines">
            <Fork id="modal">
                <Fork>
                    <Selector>
                        <ImageLayer id="artifact">
                            <conditions>
                                <IsEquals key="colorless_artifact"/>
                                <IsPresent key="proximity.types.land" value="false"/>
                            </conditions>
                        </ImageLayer>
                        <ImageLayer id="colorless">
                            <conditions>
                                <IsEquals key="proximity.color_count" value="0"/>
                            </conditions>
                        </ImageLayer>
                        <ImageLayer id="colored" src="${colors}">
                            <conditions>
                                <IsEquals key="one_or_two_colors"/>
                            </conditions>
                        </ImageLayer>
                        <ImageLayer id="gold"/>
                    </Selector>
                    <branches>
                        <Branch id="land">
                            <IsPresent key="proximity.types.land"/>
                        </Branch>
                        <Branch id="standard"/>
                    </branches>
                </Fork>
                <branches>
                    <Branch id="front">
                        <IsEquals key="proximity.front_face"/>
                    </Branch>
                    <Branch id="back">
                        <IsEquals key="proximity.front_face" value="false"/>
                    </Branch>
                </branches>
                <conditions>
                    <IsEquals key="layout" value="modal_dfc"/>
                </conditions>
            </Fork>
            <Fork id="transform">
                <Selector>
                    <ImageLayer id="artifact">
                        <conditions>
                            <IsEquals key="colorless_artifact"/>
                            <IsPresent key="proximity.types.land" value="false"/>
                        </conditions>
                    </ImageLayer>
                    <ImageLayer id="colorless">
                        <conditions>
                            <IsEquals key="proximity.color_count" value="0"/>
                        </conditions>
                    </ImageLayer>
                    <ImageLayer id="colored" src="${colors}">
                        <conditions>
                            <IsEquals key="one_or_two_colors"/>
                        </conditions>
                    </ImageLayer>
                    <ImageLayer id="gold"/>
                </Selector>
                <branches>
                    <Branch id="front">
                        <IsEquals key="proximity.front_face"/>
                    </Branch>
                    <Branch id="back">
                        <IsEquals key="proximity.front_face" value="false"/>
                    </Branch>
                </branches>
                <conditions>
                    <IsEquals key="layout" value="transform"/>
                </conditions>
            </Fork>
            <ImageLayer id="miracle" src="miracle/${colors}">
                <conditions>
                    <IsPresent key="frame_effects.miracle"/>
                    <IsEquals key="proximity.color_count" value="0"/>
                </conditions>
            </ImageLayer>
            <Selector id="mutate">
                <ImageLayer id="colorless">
                    <conditions>
                        <IsEquals key="colorless_artifact"/>
                        <IsPresent key="proximity.types.land" value="false"/>
                    </conditions>
                </ImageLayer>
                <ImageLayer id="colored">
                    <conditions>
                        <IsEquals key="one_or_two_colors"/>
                    </conditions>
                </ImageLayer>
                <ImageLayer id="gold"/>
                <conditions>
                    <IsPresent key="keywords.mutate"/>
                </conditions>
            </Selector>
            <Fork id="standard">
                <Selector>
                    <ImageLayer id="artifact">
                        <conditions>
                            <IsEquals key="colorless_artifact"/>
                            <IsPresent key="proximity.types.land" value="false"/>
                        </conditions>
                    </ImageLayer>
                    <ImageLayer id="colorless">
                        <conditions>
                            <IsEquals key="proximity.color_count" value="0"/>
                        </conditions>
                    </ImageLayer>
                    <ImageLayer id="colored" src="${colors}">
                        <conditions>
                            <IsEquals key="one_or_two_colors"/>
                        </conditions>
                    </ImageLayer>
                    <ImageLayer id="gold"/>
